import type { AccountRole } from "@/lib/auth/roles";
import type { InteractiveMessagePayload } from "@/lib/whatsapp/interactive";

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from "@/lib/whatsapp/interactive";

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, "owner">;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  email?: string;
  company?: string;
  avatar_url?: string;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

/**
 * Anotação interna da conversa (migration 918). Nunca sai para o cliente:
 * aparece no fio do chat e nas duas fichas do contato.
 *
 * Aposentou a `ContactNote`/`contact_notes`, que saiu daqui junto com o
 * último call site — tipo sem dono descrevendo tabela sem leitor é convite
 * para alguém "consertar" a tela errada. A chave é a CONVERSA porque é a
 * única que cobre conversa 1:1 e conversa de grupo (grupo não tem contato).
 *
 * ⚠️ Não tem `updated_at` de propósito: a anotação é criada e apagada, nunca
 * editada. O banco reforça isso com `REVOKE UPDATE`.
 */
export interface ConversationNote {
  id: string;
  account_id: string;
  conversation_id: string;
  /** Nulo em conversa de grupo. */
  contact_id: string | null;
  /** Nulo quando o autor saiu do `auth.users`. */
  author_user_id: string | null;
  /** Carimbado na escrita — o autor pode sair da conta e sumir do `profiles`. */
  autor_nome: string | null;
  texto: string;
  /** `auth.users.id` dos colegas mencionados. */
  mencionados: string[];
  created_at: string;
}

/**
 * Situação de uma mensagem agendada (migration 925).
 *
 * ⚠️ `sending` parado é o estado que engana. Ele significa "o worker
 * reivindicou a linha e não voltou" — o processo morreu no meio, e a mensagem
 * PODE ter saído para o cliente. Por isso não existe retentativa a partir
 * dele: a saída é a pessoa apagar e reagendar, decidindo com o que vê na
 * conversa. Retentar dali é a receita para o cliente receber duas vezes.
 */
export type ScheduledMessageStatus = 'pending' | 'sending' | 'sent' | 'failed';

/**
 * Mensagem escrita agora para sair na hora marcada (migration 925). Só texto
 * na v1 (P4.6).
 *
 * ⚠️ Nada dispara sozinho: a linha só sai porque alguém de fora bate em
 * `/api/cb/scheduled/cron`. Sem o agendador na VPS esta tabela é uma coluna
 * morta, exatamente como `broadcasts.scheduled_at` é desde a 001.
 */
export interface ScheduledMessage {
  id: string;
  account_id: string;
  /** A chave é a CONVERSA — é a única que cobre 1:1 e grupo. */
  conversation_id: string;
  /**
   * O número por onde ESTA mensagem sai, fixado no agendamento. Não segue a
   * conversa: se o cliente escrever por outro número no meio-tempo, a
   * agendada continua saindo por este (P4.3).
   */
  channel_id: string;
  body: string;
  scheduled_for: string;
  status: ScheduledMessageStatus;
  /** Motivo da falha, em texto para o operador ler (P4.9). */
  error: string | null;
  /**
   * O envio falhou DEPOIS de o WhatsApp já ter aceitado a mensagem (926).
   *
   * ⚠️ É o que separa "não saiu" de "saiu e não foi gravado". Com isto
   * ligado, a tela NÃO oferece "Tentar de novo": um clique mandaria a mesma
   * coisa duas vezes para o cliente.
   */
  entrega_incerta: boolean;
  /** `messages.id` do que realmente saiu. */
  message_id: string | null;
  /** Nulo quando quem agendou saiu do `auth.users`. */
  created_by: string | null;
  /** Carimbado na escrita — sobrevive à saída do membro. */
  autor_nome: string;
  created_at: string;
  sent_at: string | null;
}

/**
 * Grupo de WhatsApp (migration 906). Existe só no transporte Evolution — a
 * API oficial da Meta não entrega mensagem de grupo.
 */
export interface CbGroup {
  id: string;
  account_id: string;
  /** Por qual número vimos este grupo. */
  channel_id: string | null;
  /** `120363…@g.us`. */
  jid: string;
  /** Nome REAL, como está no WhatsApp. NULL até a sincronização resolver. */
  subject: string | null;
  /**
   * Apelido só nosso, invisível para os participantes. Tem precedência sobre
   * `subject` na exibição — ver `nomeDoGrupo`.
   */
  alias: string | null;
  description: string | null;
  picture_url: string | null;
  owner_jid: string | null;
  participant_count: number | null;
  /** "Só administradores podem enviar". */
  is_announce: boolean | null;
  /** Libera renomear de verdade. NULL = ainda não sincronizamos. */
  we_are_admin: boolean | null;
  synced_at: string | null;
  created_at: string;
  updated_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  user_id: string;
  /**
   * NULL em conversa de GRUPO (migration 906 tirou o NOT NULL). O tipo é
   * anulável de propósito: fingir que sempre existe daria um `string` que na
   * verdade é null em tempo de execução, sem o compilador avisar ninguém.
   * O par contato/grupo é exclusivo — ver `group_id` abaixo.
   */
  contact_id: string | null;
  status: ConversationStatus;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact | null;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
  /**
   * Multi-canal (migration 902): por qual número (cb_channels) a conversa
   * responde. `channel_pinned` = o atendente fixou o canal na mão; enquanto
   * false, o inbound move `channel_id` para o canal da última mensagem do
   * cliente ("segue o cliente").
   */
  channel_id?: string | null;
  channel_pinned?: boolean;
  /**
   * Grupos (migration 906): preenchido quando a conversa é de um grupo de
   * WhatsApp. O banco garante o ou-um-ou-outro pelo CHECK
   * `cb_conv_contato_xor_grupo` — ver `contact_id` acima.
   */
  group_id?: string | null;
  /** Hidratado pelo `CONVERSATION_SELECT`, do mesmo jeito que `contact`. */
  group?: CbGroup | null;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

/**
 * ⚠️ Espelha o CHECK de `notifications.type`. Alargar aqui sem alargar o
 * banco (ou o contrário) só aparece em runtime, como violação de constraint.
 * Os literais vivem na 027 (`conversation_assigned`) e na 919 (`note_mention`).
 *
 * ⚠️ Não confundir com o `'conversation_assigned'` homônimo mais abaixo neste
 * arquivo, que é gatilho de AUTOMAÇÃO. São coisas diferentes com o mesmo nome.
 */
export type NotificationType = 'conversation_assigned' | 'note_mention';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive'
  /**
   * Aviso do próprio WhatsApp dentro de um grupo ("Fulano entrou", "o nome
   * mudou"). Não é mensagem de ninguém: renderiza como faixa cinza no meio da
   * conversa, em ordem cronológica. Migration 906.
   */
  | 'system';
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
  /** Canal (cb_channels) por onde esta mensagem entrou/saiu. Migration 902. */
  channel_id?: string | null;
  /**
   * Enviada pelo APARELHO pareado (WhatsApp no celular), não pelo CRM. Só
   * acontece em canal Evolution, onde os dois dividem a mesma conta de
   * WhatsApp. A bolha marca essas mensagens porque, num número atendido por
   * várias pessoas, importa saber que aquela resposta não passou pelo
   * sistema. Migration 904.
   */
  from_device?: boolean;
  /**
   * Apagada no WhatsApp. O conteúdo PERMANECE em `content_text` de
   * propósito: o CRM mostra riscado em vez de esconder, porque o escritório
   * precisa do registro do que foi dito — inclusive do que o cliente apagou
   * depois. Divergência deliberada do WhatsApp. Migration 905.
   */
  deleted_at?: string | null;
  /**
   * O CRM PEDIU a revogação e ainda não teve confirmação. Migration 907.
   *
   * Não é sinônimo de `deleted_at`: o WhatsApp não confirma revogação, e a
   * resposta 2xx da Evolution só diz que ela aceitou o pedido. A bolha risca
   * nos dois casos, mas só `deleted_at` autoriza escrever "Apagada" — com
   * este campo sozinho, o texto honesto é "Exclusão solicitada".
   */
  delete_requested_at?: string | null;
  /** Quem apagou: 'customer' = o cliente; 'agent' = nós. Migration 905. */
  deleted_by?: 'customer' | 'agent' | null;
  /** Editada no WhatsApp. Migration 905. */
  edited_at?: string | null;
  /** Texto anterior à última edição — o WhatsApp não guarda histórico. */
  text_before_edit?: string | null;
  /**
   * Quem falou, quando a conversa é de GRUPO. Desnormalizado de propósito —
   * sem FK para `contacts`, senão um grupo de 80 pessoas criaria 80 contatos
   * no CRM na primeira mensagem. Ambos NULL em conversa 1:1. Migration 906.
   */
  group_sender_jid?: string | null;
  group_sender_name?: string | null;
  /** Marcaram o nosso número nesta mensagem de grupo. Migration 906. */
  mentions_us?: boolean;
  /**
   * Estado do anexo quando ele NÃO está no nosso Storage. `null` = sem mídia
   * ou já baixada (aí `media_url` está preenchido); `'pending'` = dá para
   * buscar sob demanda; `'failed'` = tentou e falhou, dá para tentar de novo;
   * `'too_large'` = acima do teto de 16 MB do bucket, não adianta tentar.
   * Migration 906.
   */
  media_state?: 'pending' | 'failed' | 'too_large' | null;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  /**
   * Which transport backs this connection (migration 037). 'meta' rows
   * carry phone_number_id + access_token; 'evolution' rows carry
   * base_url + instance_name + api_key. A CHECK enforces the pairing.
   */
  provider: 'meta' | 'evolution';
  status: 'connected' | 'disconnected';
  connected_at?: string;

  // --- Meta Cloud API fields (provider = 'meta') -------------
  /** Nullable since 037 — only present on Meta rows. */
  phone_number_id?: string;
  waba_id?: string;
  /** Encrypted Meta token. Nullable since 037 — only on Meta rows. */
  access_token?: string;
  verify_token?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;

  // --- Evolution API fields (provider = 'evolution') ---------
  /** Evolution server origin, e.g. `https://api.cbadvogados.com`. */
  base_url?: string;
  /** Evolution instance name (also the inbound-routing key). */
  instance_name?: string;
  /** Encrypted Evolution instance apikey (the instance `hash`/token). */
  api_key?: string;
  /** Baileys connection state from the last poll / connection.update. */
  instance_state?: 'open' | 'connecting' | 'close';
  last_connected_at?: string;
  last_connection_error?: string;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  /**
   * Canal (WABA) a que este modelo pertence (migration 903). `null` = modelo
   * global, anterior ao multi-canal — ele serve qualquer canal Meta até ser
   * adotado por um na primeira sincronização.
   *
   * ⚠️ Desde a 903 o par `(name, language)` só é único DENTRO do canal: o
   * mesmo nome de modelo pode existir em dois WABAs. Consulta sem recorte de
   * canal estoura com "multiple rows".
   */
  channel_id?: string | null;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

/** Quem criou o negócio. Espelha o CHECK de `deals.source` (migration 908). */
export type DealSource = 'manual' | 'automation' | 'channel';

export interface Deal {
  id: string;
  /**
   * Anulável desde a 908 (`ON DELETE SET NULL`): os cards criados pelo
   * roteador pertencem todos ao dono da conta, e o CASCADE anterior apagaria
   * o funil inteiro se essa pessoa saísse do `auth.users`.
   */
  user_id: string | null;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  /**
   * Conversa de onde o card nasceu (escrito desde a 910) — é o caminho de
   * volta do Kanban para o atendimento. `null` em negócio criado à mão antes
   * da 910 e quando a conversa é apagada.
   */
  conversation_id?: string | null;
  /**
   * Por qual número o cliente CHEGOU (migration 908). É histórico: NÃO muda
   * quando o card é movido para outro funil. `null` em negócio criado à mão.
   */
  channel_id?: string | null;
  /** Quem criou o card (migration 908). */
  source?: DealSource;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
}

export type BroadcastStatus = 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus = 'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  /**
   * Número (canal Meta) de onde a campanha saiu, migration 903. `null` nas
   * campanhas anteriores ao multi-canal — o relatório mostra travessão em
   * vez de chutar o padrão atual, que pode nem ser o de então.
   */
  channel_id?: string | null;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply';

export type AutomationStepType =
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  match_type: 'exact' | 'contains';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | Record<string, unknown>;

/**
 * Canal de SAÍDA opcional, comum a todo passo que envia mensagem.
 *
 * Ausente/`null` = usa o canal do DISPARO (o número por onde o cliente
 * escreveu), com queda para o canal atual da conversa. Preenchido = força
 * aquele número — é o "envie a confirmação formal SEMPRE pelo número oficial,
 * mesmo que o cliente tenha escrito no celular do advogado".
 */
export interface ChannelScopedStepConfig {
  channel_id?: string | null;
}

export interface SendMessageStepConfig extends ChannelScopedStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig extends ChannelScopedStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  | 'contact_field'
  | 'tag_presence'
  | 'message_content'
  | 'time_of_day'
  /** Compara o canal do disparo com `operand` (um cb_channels.id). */
  | 'channel';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  /**
   * Canais (`cb_channels.id`) em que esta automação pode disparar.
   * `null`/ausente = TODOS os canais — o comportamento de antes do
   * multi-canal, e o que toda automação existente continua tendo.
   *
   * Array vazio é estado inválido: significaria "nenhum canal", mas o
   * dispatch o leria como "sem restrição". O trigger
   * `cb_channels_drop_from_automations` (migration 903) normaliza para NULL
   * e DESATIVA a automação quando o último canal do escopo é removido.
   */
  channel_ids?: string[] | null;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
  /**
   * Canal por onde este disparo entrou (migration 903). `null` nos
   * registros anteriores ao multi-canal — a tela mostra travessão, e não o
   * canal padrão, porque naquela época o disparo pode ter vindo de outro
   * número.
   */
  channel_id?: string | null;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Histórico de atividade do lead (migration 912)
//
// Trilha append-only escrita por trigger no Postgres. `authenticated` só tem
// SELECT — nenhum código do app escreve aqui, e tentar escrever devolve 42501.
// ============================================================

export type LeadEventType =
  | 'deal_created'
  | 'stage_changed'
  | 'pipeline_changed'
  | 'status_changed'
  | 'deal_deleted'
  | 'tag_added'
  | 'tag_removed';

/**
 * De onde partiu a mudança. `sistema` é escrita server-side sem ator
 * identificável (API pública, fluxo, manutenção) — o trigger não consegue
 * distinguir esses casos por dentro, e a trilha não deve prometer mais do que
 * sabe. `retroativo` é linha reconstruída pela própria migration.
 */
export type LeadEventOrigin =
  | 'usuario'
  | 'conexao'
  | 'automacao'
  | 'sistema'
  | 'retroativo';

export interface LeadEvent {
  id: string;
  account_id: string;
  /** `null` depois que o contato é apagado — o rótulo abaixo sobrevive. */
  contact_id: string | null;
  contact_label: string | null;
  /** Sem FK: `deal_deleted` aponta para um negócio que já não existe. */
  deal_id: string | null;
  conversation_id: string | null;
  event_type: LeadEventType;
  occurred_at: string;
  actor_user_id: string | null;
  /** Nome de quem agiu, congelado no momento do evento. */
  actor_label: string | null;
  origin: LeadEventOrigin;
  from_pipeline_id: string | null;
  from_pipeline_label: string | null;
  to_pipeline_id: string | null;
  to_pipeline_label: string | null;
  from_stage_id: string | null;
  from_stage_label: string | null;
  /** Responde "foi avanço ou foi volta?" — o rótulo sozinho não responde. */
  from_stage_position: number | null;
  to_stage_id: string | null;
  to_stage_label: string | null;
  to_stage_position: number | null;
  from_status: string | null;
  to_status: string | null;
  tag_id: string | null;
  tag_label: string | null;
  tag_color: string | null;
  channel_id: string | null;
  channel_label: string | null;
  /** `true` = linha reconstruída do estado atual, não observada acontecendo. */
  reconstructed: boolean;
  details: Record<string, unknown> | null;
  created_at: string;
}
