import type { AccountRole } from '@/lib/auth/roles';
import type { InteractiveMessagePayload } from '@/lib/whatsapp/interactive';

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from '@/lib/whatsapp/interactive';

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, 'owner'>;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  email?: string;
  company?: string;
  avatar_url?: string;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  /**
   * 'text' | 'datetime' | 'select' | 'number' — fechado por CHECK desde a
   * 948. Fica `string` no tipo porque linhas antigas chegam do PostgREST
   * antes de qualquer validação nossa.
   */
  field_type: string;
  /**
   * Identificador estável por conta (migration 948) — o que a API pública
   * usará para referenciar o campo. Gerado por gatilho quando ausente;
   * NUNCA substitui o UUID nos consumidores internos (automações, lembrete,
   * broadcast seguem por id).
   */
  field_key: string;
  /** `{ opcoes: string[] }` num campo `select`; livre/nulo nos demais. */
  field_options?: Record<string, unknown>;
  /**
   * 'geral' | 'tracking' (CHECK da 949).
   *
   * ⚠️ NÃO é o bloco em que o campo aparece — isso é `grupo_id` (966). Esta
   * coluna sobrevive como marca SEMÂNTICA ("é campo técnico"): é o que o
   * semeador dos 10 campos padrão escreve e o que a API pública v1 expõe como
   * `category` desde a Fase 6. O seletor de categoria saiu do formulário de
   * criação; campo criado à mão nasce 'geral'.
   */
  categoria: string;
  /**
   * Bloco em que o campo aparece na ficha do cliente (966). `null` é o bloco
   * "Geral", que não tem linha em `cb_grupos_de_campos` e vem sempre primeiro.
   */
  grupo_id?: string | null;
  /**
   * Ordem DENTRO do bloco (966). `null` cai no fim — é o que acontece com
   * campo criado por um caminho que não carimba a posição (o semeador de
   * traqueamento, por exemplo).
   */
  posicao?: number | null;
  created_at: string;
}

/**
 * Bloco de campos personalizados (migration 966) — "Bancário", "Trabalhista",
 * "Traqueamento". É só rótulo + ordem: quem pertence a ele é
 * `custom_fields.grupo_id`.
 *
 * O bloco "Geral" NÃO tem linha aqui: ele é o `grupo_id IS NULL`, e por isso
 * não é renomeável nem arrastável. Ver `src/lib/contacts/grupos-de-campos.ts`.
 */
export interface GrupoDeCampos {
  id: string;
  account_id: string;
  nome: string;
  /** Ordem entre blocos. Empate desempata pelo nome. */
  posicao: number;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

/**
 * Anotação interna da conversa (migration 918). Nunca sai para o cliente:
 * aparece no fio do chat e nas duas fichas do contato.
 *
 * Aposentou a `ContactNote`/`contact_notes`, que saiu daqui junto com o
 * último call site — tipo sem dono descrevendo tabela sem leitor é convite
 * para alguém "consertar" a tela errada. A chave é a CONVERSA porque é a
 * única que cobre conversa 1:1 e conversa de grupo (grupo não tem contato).
 *
 * ⚠️ Não tem `updated_at` de propósito: a anotação é criada e apagada, nunca
 * editada. O banco reforça isso com `REVOKE UPDATE`.
 */
/**
 * Um item do acervo de mídias da conta (migration 953).
 *
 * ⚠️ `media_url` é DERIVADA de `media_path` no servidor — nunca aceita do
 * navegador. Ver a rota `POST /api/cb/acervo`.
 */
export interface MediaLibraryItem {
  id: string;
  account_id: string;
  titulo: string;
  /** NULL = sem categoria; a tela mostra "Geral". */
  categoria: string | null;
  tipo: "image" | "video" | "document" | "audio";
  /** Caminho no bucket `chat-media`, sob `account-<id>/acervo/`. */
  media_path: string;
  media_url: string;
  mime_type: string;
  size_bytes: number;
  filename: string;
  /** NULL quando quem subiu saiu da conta. */
  criador_user_id: string | null;
  /** Congelado na escrita — sobrevive à saída de quem subiu. */
  criador_nome: string | null;
  created_at: string;
  updated_at: string;
}

export interface ConversationNote {
  id: string;
  account_id: string;
  conversation_id: string;
  /** Nulo em conversa de grupo. */
  contact_id: string | null;
  /** Nulo quando o autor saiu do `auth.users`. */
  author_user_id: string | null;
  /** Carimbado na escrita — o autor pode sair da conta e sumir do `profiles`. */
  autor_nome: string | null;
  texto: string;
  /** `auth.users.id` dos colegas mencionados. */
  mencionados: string[];
  /**
   * Quando a nota foi FIXADA no topo da ficha (951). NULL = comum. No
   * máximo uma por contato — índice parcial no banco; a escrita é só pela
   * rota `/api/cb/notes/[id]` (UPDATE segue revogado no navegador).
   */
  fixada_em: string | null;
  created_at: string;
}

/**
 * Situação de uma mensagem agendada (migration 925).
 *
 * ⚠️ `sending` parado é o estado que engana. Ele significa "o worker
 * reivindicou a linha e não voltou" — o processo morreu no meio, e a mensagem
 * PODE ter saído para o cliente. Por isso não existe retentativa a partir
 * dele: a saída é a pessoa apagar e reagendar, decidindo com o que vê na
 * conversa. Retentar dali é a receita para o cliente receber duas vezes.
 */
export type ScheduledMessageStatus = 'pending' | 'sending' | 'sent' | 'failed';

/**
 * Mensagem escrita agora para sair na hora marcada (migration 925). Só texto
 * na v1 (P4.6).
 *
 * ⚠️ Nada dispara sozinho: a linha só sai porque alguém de fora bate em
 * `/api/cb/scheduled/cron`. Sem o agendador na VPS esta tabela é uma coluna
 * morta, exatamente como `broadcasts.scheduled_at` é desde a 001.
 */
export interface ScheduledMessage {
  id: string;
  account_id: string;
  /** A chave é a CONVERSA — é a única que cobre 1:1 e grupo. */
  conversation_id: string;
  /**
   * O número por onde ESTA mensagem sai, fixado no agendamento. Não segue a
   * conversa: se o cliente escrever por outro número no meio-tempo, a
   * agendada continua saindo por este (P4.3).
   */
  channel_id: string;
  body: string;
  scheduled_for: string;
  status: ScheduledMessageStatus;
  /** Motivo da falha, em texto para o operador ler (P4.9). */
  error: string | null;
  /**
   * O envio falhou DEPOIS de o WhatsApp já ter aceitado a mensagem (926).
   *
   * ⚠️ É o que separa "não saiu" de "saiu e não foi gravado". Com isto
   * ligado, a tela NÃO oferece "Tentar de novo": um clique mandaria a mesma
   * coisa duas vezes para o cliente.
   */
  entrega_incerta: boolean;
  /**
   * Anexo (932). Os três primeiros andam juntos — CHECK de forma no banco.
   *
   * ⚠️ O arquivo já está no bucket desde o momento em que foi ANEXADO, não do
   * envio. Entre uma coisa e outra passam horas, e o objeto pode sumir: quem
   * confere é o disparador, antes de reivindicar a linha.
   */
  media_url: string | null;
  /** Caminho no bucket `chat-media` — para conferir e para apagar ao cancelar. */
  media_path: string | null;
  media_kind: 'image' | 'video' | 'document' | 'audio' | null;
  /** Só o documento mostra o nome ao destinatário. */
  media_filename: string | null;
  /**
   * A mensagem que esta agendada responde (932). Sem FK, de propósito — ver a
   * migration.
   */
  reply_to_message_id: string | null;
  /**
   * A citada não existia mais na hora do envio, e a mensagem saiu SEM ela.
   *
   * ⚠️ Existe porque o `NULL` sozinho não distingue "nunca citou" de "citava e
   * perdeu" — e é a segunda que precisa aparecer na tela. Mesma lição da
   * `entrega_incerta`.
   */
  citacao_perdida: boolean;
  /** `messages.id` do que realmente saiu. */
  message_id: string | null;
  /** Nulo quando quem agendou saiu do `auth.users`. */
  created_by: string | null;
  /** Carimbado na escrita — sobrevive à saída do membro. */
  autor_nome: string;
  created_at: string;
  sent_at: string | null;
}

/**
 * Grupo de WhatsApp (migration 906). Existe só no transporte Evolution — a
 * API oficial da Meta não entrega mensagem de grupo.
 */
export interface CbGroup {
  id: string;
  account_id: string;
  /** Por qual número vimos este grupo. */
  channel_id: string | null;
  /** `120363…@g.us`. */
  jid: string;
  /** Nome REAL, como está no WhatsApp. NULL até a sincronização resolver. */
  subject: string | null;
  /**
   * Apelido só nosso, invisível para os participantes. Tem precedência sobre
   * `subject` na exibição — ver `nomeDoGrupo`.
   */
  alias: string | null;
  description: string | null;
  picture_url: string | null;
  owner_jid: string | null;
  participant_count: number | null;
  /** "Só administradores podem enviar". */
  is_announce: boolean | null;
  /** Libera renomear de verdade. NULL = ainda não sincronizamos. */
  we_are_admin: boolean | null;
  synced_at: string | null;
  created_at: string;
  updated_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  user_id: string;
  /**
   * NULL em conversa de GRUPO (migration 906 tirou o NOT NULL). O tipo é
   * anulável de propósito: fingir que sempre existe daria um `string` que na
   * verdade é null em tempo de execução, sem o compilador avisar ninguém.
   * O par contato/grupo é exclusivo — ver `group_id` abaixo.
   */
  contact_id: string | null;
  status: ConversationStatus;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact | null;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
  /**
   * Multi-canal (migration 902): por qual número (cb_channels) a conversa
   * responde. `channel_pinned` = o atendente fixou o canal na mão; enquanto
   * false, o inbound move `channel_id` para o canal da última mensagem do
   * cliente ("segue o cliente").
   */
  channel_id?: string | null;
  channel_pinned?: boolean;
  /**
   * Grupos (migration 906): preenchido quando a conversa é de um grupo de
   * WhatsApp. O banco garante o ou-um-ou-outro pelo CHECK
   * `cb_conv_contato_xor_grupo` — ver `contact_id` acima.
   */
  group_id?: string | null;
  /** Hidratado pelo `CONVERSATION_SELECT`, do mesmo jeito que `contact`. */
  group?: CbGroup | null;
  /**
   * Desde quando o CLIENTE espera resposta de gente (migration 972). Mantida
   * por gatilho: mensagem do cliente preenche se vazia, resposta humana
   * (`sender_id` OU `from_device`) limpa, encerrar limpa. NULL = ninguém
   * esperando. A lista lê pela régua de `src/lib/inbox/atraso.ts`.
   */
  aguardando_desde?: string | null;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

/**
 * ⚠️ Espelha o CHECK de `notifications.type`. Alargar aqui sem alargar o
 * banco (ou o contrário) só aparece em runtime, como violação de constraint.
 * Os literais vivem na 027 (`conversation_assigned`), na 919 (`note_mention`)
 * e na 944 (`task_assigned`, `task_reply`).
 *
 * ⚠️ Não confundir com o `'conversation_assigned'` homônimo mais abaixo neste
 * arquivo, que é gatilho de AUTOMAÇÃO. São coisas diferentes com o mesmo nome.
 */
export type NotificationType =
  'conversation_assigned' | 'note_mention' | 'task_assigned' | 'task_reply';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  /** A tarefa que o aviso abre (944). Só nos tipos `task_*`. */
  task_id?: string;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

// ============================================================
// Tarefas (migration 944)
// ============================================================

/**
 * ⚠️ Espelha o CHECK de `cb_tasks.status`. Duas situações só, de propósito:
 * "em andamento" seria um terceiro estado que ninguém atualiza — quem está
 * fazendo a tarefa está fazendo, não registrando que está.
 */
export type TaskStatus = 'aberta' | 'concluida';

/**
 * ⚠️ Espelha o CHECK de `cb_tasks.tipo`.
 *
 * `resposta` é a devolutiva que volta para quem delegou; `tarefa` cobre todo o
 * resto, inclusive o desdobramento ("não atendeu, retentar terça"), que é
 * tarefa de pleno direito — só que com `tarefa_pai_id` preenchido.
 */
export type TaskKind = 'tarefa' | 'resposta';

/**
 * Tarefa sobre um cliente, encaminhada a um colega (migration 944).
 *
 * ⚠️ O navegador só LÊ esta tabela. Toda escrita passa por `/api/cb/tasks`,
 * porque criar tarefa grava em `notifications` (que não aceita INSERT do
 * cliente desde a 027) e porque as regras de quem-pode-o-quê moram em
 * `src/lib/tasks/permissoes.ts`, num lugar só.
 *
 * ⚠️ Não guarda `conversation_id`: a conversa é derivada do contato na tela
 * (UNIQUE em `(account_id, contact_id)` desde a 036). Uma segunda cópia
 * envelheceria quando a conversa fosse apagada e recriada.
 */
export interface Task {
  id: string;
  account_id: string;
  /** O cliente de quem a tarefa fala. Nunca nulo — grupo não recebe tarefa. */
  contact_id: string;
  /** Nulo quando quem criou saiu do `auth.users`. */
  criador_user_id: string | null;
  /** Nulo quando o responsável saiu do `auth.users`. */
  responsavel_user_id: string | null;
  /** Carimbados na escrita — quem sai da conta some do `profiles`. */
  criador_nome: string | null;
  responsavel_nome: string | null;
  titulo: string;
  descricao: string | null;
  /**
   * `YYYY-MM-DD`, coluna `date` do Postgres.
   *
   * ⚠️ NUNCA passar por `new Date(vence_em)` direto: a string sem hora é
   * interpretada como meia-noite UTC e no Brasil retrocede um dia — a
   * armadilha que o CLAUDE.md documenta para `expected_close_date`. Use os
   * helpers de `src/lib/tasks/prazo.ts`.
   */
  vence_em: string;
  /** `HH:MM:SS` ou nulo — a hora é opcional por pedido do operador. */
  vence_as: string | null;
  status: TaskStatus;
  /** Anda junto com `status` — CHECK de forma no banco. */
  concluida_em: string | null;
  /** Leitura DO RESPONSÁVEL, alternável nos dois sentidos. */
  lida_em: string | null;
  importante: boolean;
  /** A tarefa de onde esta saiu. Nulo se não houve, ou se a origem foi apagada. */
  tarefa_pai_id: string | null;
  /** Congelado: sobrevive à exclusão da origem, que é `ON DELETE SET NULL`. */
  tarefa_pai_titulo: string | null;
  tipo: TaskKind;
  created_at: string;
  updated_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive'
  /**
   * Aviso do próprio WhatsApp dentro de um grupo ("Fulano entrou", "o nome
   * mudou"). Não é mensagem de ninguém: renderiza como faixa cinza no meio da
   * conversa, em ordem cronológica. Migration 906.
   */
  | 'system';
export type MessageStatus =
  'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  /**
   * MIME type of `media_url`'s content, as Meta reported it. Inbound
   * media only — outbound URLs already carry a filename and extension.
   * Null on every row written before migration 042.
   *
   * ⚠️ Era NULL em 100% das linhas até a 969: a coluna existia desde a 042,
   * mas só o caminho da Meta a escrevia, e produção roda Evolution.
   */
  media_type?: string | null;
  /**
   * Nome do arquivo como o remetente o enviou (migration 969) — o que o
   * WhatsApp mostra na bolha. NULL em mensagem sem anexo, em mídia que não
   * tem nome (foto, vídeo, áudio) e em toda linha anterior à 969.
   *
   * ⚠️ Não leia esta coluna direto para exibir: use `mediaFilename()` de
   * `@/lib/media/filename`, que cai para o caminho do Storage quando ela é
   * nula — é o que recupera o nome dos 188 documentos históricos.
   */
  media_filename?: string | null;
  /**
   * Transcrição da nota de voz (migration 943) — NUNCA em `content_text`:
   * o que o cliente escreveu e o que a máquina ouviu são coisas
   * diferentes, e num CRM jurídico a distinção é permanente. Estados:
   * NULL (nunca pedida) → transcrevendo → pronta | falhou (retentável) |
   * recusada (terminal, sem botão).
   */
  transcricao?: string | null;
  transcricao_status?:
    'transcrevendo' | 'pronta' | 'falhou' | 'recusada' | null;
  transcricao_erro?: string | null;
  /** Carimbo do claim — a bolha o usa para reoferecer o botão quando um
   *  "transcrevendo" ficou órfão (processo morto no deploy). */
  transcricao_desde?: string | null;
  transcricao_em?: string | null;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
  /** Canal (cb_channels) por onde esta mensagem entrou/saiu. Migration 902. */
  channel_id?: string | null;
  /**
   * Enviada pelo APARELHO pareado (WhatsApp no celular), não pelo CRM. Só
   * acontece em canal Evolution, onde os dois dividem a mesma conta de
   * WhatsApp. A bolha marca essas mensagens porque, num número atendido por
   * várias pessoas, importa saber que aquela resposta não passou pelo
   * sistema. Migration 904.
   */
  from_device?: boolean;
  /**
   * Apagada no WhatsApp. O conteúdo PERMANECE em `content_text` de
   * propósito: o CRM mostra riscado em vez de esconder, porque o escritório
   * precisa do registro do que foi dito — inclusive do que o cliente apagou
   * depois. Divergência deliberada do WhatsApp. Migration 905.
   */
  deleted_at?: string | null;
  /**
   * O CRM PEDIU a revogação e ainda não teve confirmação. Migration 907.
   *
   * Não é sinônimo de `deleted_at`: o WhatsApp não confirma revogação, e a
   * resposta 2xx da Evolution só diz que ela aceitou o pedido. A bolha risca
   * nos dois casos, mas só `deleted_at` autoriza escrever "Apagada" — com
   * este campo sozinho, o texto honesto é "Exclusão solicitada".
   */
  delete_requested_at?: string | null;
  /** Quem apagou: 'customer' = o cliente; 'agent' = nós. Migration 905. */
  deleted_by?: 'customer' | 'agent' | null;
  /** Editada no WhatsApp. Migration 905. */
  edited_at?: string | null;
  /** Texto anterior à última edição — o WhatsApp não guarda histórico. */
  text_before_edit?: string | null;
  /**
   * Quem falou, quando a conversa é de GRUPO. Desnormalizado de propósito —
   * sem FK para `contacts`, senão um grupo de 80 pessoas criaria 80 contatos
   * no CRM na primeira mensagem. Ambos NULL em conversa 1:1. Migration 906.
   */
  group_sender_jid?: string | null;
  group_sender_name?: string | null;
  /** Marcaram o nosso número nesta mensagem de grupo. Migration 906. */
  mentions_us?: boolean;
  /**
   * Estado do anexo quando ele NÃO está no nosso Storage. `null` = sem mídia
   * ou já baixada (aí `media_url` está preenchido); `'pending'` = dá para
   * buscar sob demanda; `'failed'` = tentou e falhou, dá para tentar de novo;
   * `'too_large'` = acima do teto de 16 MB do bucket, não adianta tentar.
   * Migration 906.
   */
  media_state?: 'pending' | 'failed' | 'too_large' | null;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  /**
   * Which transport backs this connection (migration 037). 'meta' rows
   * carry phone_number_id + access_token; 'evolution' rows carry
   * base_url + instance_name + api_key. A CHECK enforces the pairing.
   */
  provider: 'meta' | 'evolution';
  status: 'connected' | 'disconnected';
  connected_at?: string;

  // --- Meta Cloud API fields (provider = 'meta') -------------
  /** Nullable since 037 — only present on Meta rows. */
  phone_number_id?: string;
  waba_id?: string;
  /** Encrypted Meta token. Nullable since 037 — only on Meta rows. */
  access_token?: string;
  verify_token?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;

  // --- Evolution API fields (provider = 'evolution') ---------
  /** Evolution server origin, e.g. `https://api.cbadvogados.com`. */
  base_url?: string;
  /** Evolution instance name (also the inbound-routing key). */
  instance_name?: string;
  /** Encrypted Evolution instance apikey (the instance `hash`/token). */
  api_key?: string;
  /** Baileys connection state from the last poll / connection.update. */
  instance_state?: 'open' | 'connecting' | 'close';
  last_connected_at?: string;
  last_connection_error?: string;
  /**
   * When true (the default), the inbound webhook copies received media
   * into the `chat-media` bucket so attachments outlive Meta's ~30-day
   * retention. Turning it off keeps storage flat and accepts that
   * inbound attachments expire. Migration 039.
   */
  mirror_inbound_media?: boolean;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  /**
   * Canal (WABA) a que este modelo pertence (migration 903). `null` = modelo
   * global, anterior ao multi-canal — ele serve qualquer canal Meta até ser
   * adotado por um na primeira sincronização.
   *
   * ⚠️ Desde a 903 o par `(name, language)` só é único DENTRO do canal: o
   * mesmo nome de modelo pode existir em dois WABAs. Consulta sem recorte de
   * canal estoura com "multiple rows".
   */
  channel_id?: string | null;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  /** NOT NULL desde a 017; faltava no tipo. */
  account_id?: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  /**
   * 'ganho' | 'perdido' | null (CHECK da 950). Entrar numa etapa marcada
   * carimba `deals.status` por GATILHO no banco — vale para qualquer
   * escritor. Sair para etapa neutra NÃO reabre (decisão do operador:
   * fechou → transfere para outro funil → continua ganho).
   */
  resultado?: string | null;
  /**
   * A que DEGRAU do funil de eficiência a etapa corresponde (migration 975):
   * 'lead' | 'mql' | 'reuniao' | 'proposta' | 'contrato' | 'perda' | null.
   * Nulo = não conta. Várias etapas podem apontar para o mesmo degrau.
   * INDEPENDENTE de `resultado` — nada deriva um do outro. O catálogo e a
   * leitura vivem em `src/lib/funil/degraus.ts`.
   */
  degrau?: string | null;
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

/** Quem criou o negócio. Espelha o CHECK de `deals.source` (migration 908). */
export type DealSource = 'manual' | 'automation' | 'channel';

export interface Deal {
  id: string;
  /** NOT NULL desde a 017; faltava no tipo. */
  account_id?: string;
  /**
   * Anulável desde a 908 (`ON DELETE SET NULL`): os cards criados pelo
   * roteador pertencem todos ao dono da conta, e o CASCADE anterior apagaria
   * o funil inteiro se essa pessoa saísse do `auth.users`.
   */
  user_id: string | null;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  /**
   * Conversa de onde o card nasceu (escrito desde a 910) — é o caminho de
   * volta do Kanban para o atendimento. `null` em negócio criado à mão antes
   * da 910 e quando a conversa é apagada.
   */
  conversation_id?: string | null;
  /**
   * Por qual número o cliente CHEGOU (migration 908). É histórico: NÃO muda
   * quando o card é movido para outro funil. `null` em negócio criado à mão.
   */
  channel_id?: string | null;
  /** Quem criou o card (migration 908). */
  source?: DealSource;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
}

export type BroadcastStatus =
  'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus =
  'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  /**
   * Número (canal Meta) de onde a campanha saiu, migration 903. `null` nas
   * campanhas anteriores ao multi-canal — o relatório mostra travessão em
   * vez de chutar o padrão atual, que pode nem ser o de então.
   */
  channel_id?: string | null;
  /**
   * Set while a server-side delivery pass is fanning out, NULL when
   * idle. Claimed with a conditional UPDATE so two resumes can't both
   * send. Added in migration 041.
   */
  delivery_locked_at?: string | null;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  /**
   * Positional body values for this recipient's template send
   * ({{1}}, {{2}}, …), frozen when the broadcast was planned so a
   * server-side resume reproduces the original pass exactly.
   * Added in migration 041; null on rows created before it.
   */
  template_params?: string[] | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply'
  /**
   * Card entrou numa etapa do funil — movido OU criado nela (migration 933).
   * É o padrão central do Kommo: cada coluna do quadro carrega suas
   * automações.
   *
   * ⚠️ Troca de FUNIL também dispara este gatilho. A trilha da 912 emite
   * `pipeline_changed` e NUNCA `stage_changed` nesse caso; escutar só
   * "mudou de etapa" perderia o movimento entre funis.
   */
  | 'deal_stage_changed'
  /** Negócio virou ganho/perdido/reaberto (migration 933). */
  | 'deal_status_changed'
  /**
   * Lembrete relativo a uma data guardada num campo personalizado do contato
   * (migration 935) — "24 horas antes da reunião".
   *
   * ⚠️ Substitui na prática o `time_based`, que nunca disparou e nem tinha
   * alvo: o motor roda por contato e "todo dia às 9h" não diz para qual.
   * Aqui a hora vem do próprio contato, então o alvo é ele.
   */
  | 'date_field_offset';

export type AutomationStepType =
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  /** Move o card para outra etapa (e outro funil, se for o caso) — 934. */
  | 'move_deal_stage'
  /** Marca o negócio ganho / perdido / reaberto — 934. */
  | 'set_deal_status'
  /** Aciona outra automação para o mesmo contato — 936. */
  | 'run_automation'
  /** Cancela as esperas paradas de uma automação para este contato — 936. */
  | 'stop_automation'
  /** Inicia um robô (fluxo); substitui o robô ativo, se houver — 936 (D11). */
  | 'run_flow'
  /** Para o robô que estiver rodando com este contato — 936. */
  | 'stop_flow'
  /** Liga ou desliga a resposta automática da IA nesta conversa — 936. */
  | 'set_ai'
  /** Envia imagem, vídeo, documento ou áudio (Fase 4). */
  | 'send_media'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  /**
   * `contains` (the default) is a raw substring test, so a short keyword
   * matches inside longer words — "k" fires on "thanks". `word` is the
   * boundary-aware alternative added for issue #409; see
   * `matchesWholeWord` in `@/lib/automations/engine` for its exact
   * semantics. Flows carry their own keyword config and stay
   * substring-only (`@/lib/flows/types`).
   */
  match_type: 'exact' | 'contains' | 'word';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

/**
 * Config do gatilho `deal_stage_changed` (migration 933).
 *
 * ⚠️ Vazio = QUALQUER etapa, nunca "nenhuma" — a convenção do projeto inteiro
 * (`channelInScope`, `findEntryFlow`, `FILTROS_VAZIOS` do inbox). Uma tela que
 * disser "nenhuma etapa" onde o motor lê "todas" faz o operador desativar a
 * regra errada.
 *
 * Só a etapa de DESTINO importa: "quando o card entrar em Proposta". De onde
 * ele veio fica no contexto, para quem quiser ramificar por condição.
 */
export interface DealStageTriggerConfig {
  /** Etapas de destino que disparam. Vazio/ausente = todas. */
  stage_ids?: string[];
}

/**
 * Config do gatilho `date_field_offset` (migration 935).
 *
 * ⚠️ `direction: 'antes'` significa disparar ANTES do valor — logo o motor
 * procura valores no FUTURO. Ver `janelaDeBusca` em
 * `src/lib/automations/lembretes.ts`, onde o sinal é tratado num lugar só.
 */
export interface DateFieldTriggerConfig {
  /**
   * De onde vem a data (947). Ausente = `'campo'`, para as automações que já
   * existiam continuarem lendo o campo personalizado sem migração de dado.
   *
   * `'reuniao'` lê `cb_meetings.starts_at` — é o que faz a reunião marcada na
   * agenda disparar lembrete sem depender de alguém preencher um campo de
   * texto. As duas fontes convivem: enquanto o Calendly preencher o campo, a
   * automação dele continua valendo.
   */
  fonte?: 'campo' | 'reuniao';
  /** `custom_fields.id` do campo de data. Só usado com `fonte: 'campo'`. */
  custom_field_id?: string;
  /** Quantas horas de distância do valor. */
  offset_hours?: number;
  /**
   * Minutos, somados às horas (947).
   *
   * ⚠️ Não é cosmético: "10 minutos antes" não cabia em `offset_hours`, e é
   * justamente o aviso de última hora que o escritório quer.
   */
  offset_minutes?: number;
  direction?: 'antes' | 'depois';
}

/** Config do gatilho `deal_status_changed` (migration 933). */
export interface DealStatusTriggerConfig {
  /** Status de destino que disparam (`won` | `lost` | `open`). Vazio = todos. */
  statuses?: string[];
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | DealStageTriggerConfig
  | DealStatusTriggerConfig
  | DateFieldTriggerConfig
  | Record<string, unknown>;

/**
 * Uma linha da fila `cb_automation_events` (migration 933).
 *
 * Existe porque quem move card está no NAVEGADOR, sob RLS, em dois caminhos
 * diferentes (arrastar no Kanban e o formulário de negócio), sem função
 * compartilhada no servidor. Um trigger de banco enche a fila; o motor drena.
 */
export interface CbAutomationEvent {
  id: string;
  account_id: string;
  tipo: 'deal_stage_changed' | 'deal_status_changed';
  /** Sem FK: apagar o negócio não pode derrubar o evento que o descreve. */
  deal_id: string | null;
  contact_id: string | null;
  /** Canal da CONVERSA do contato, não o do nascimento do card (D9). */
  channel_id: string | null;
  from_pipeline_id: string | null;
  to_pipeline_id: string | null;
  from_stage_id: string | null;
  to_stage_id: string | null;
  from_status: string | null;
  to_status: string | null;
  origem: 'usuario' | 'conexao' | 'automacao' | 'sistema';
  /**
   * Por onde este encadeamento já passou (migration 934), como chaves
   * `deal:<id>|stage:<id>`. Vazia = ação de gente/conexão, cadeia nova.
   *
   * ⚠️ É a guarda ANTI-CICLO, e não um contador: o operador recusou teto de
   * profundidade porque esteira longa é legítima. O drenador recusa o evento
   * cuja chave já esteja aqui — X→Y→X para na segunda volta, e uma esteira de
   * 20 etapas passa inteira.
   */
  cadeia: string[];
  criado_em: string;
  /** NULL = pendente. É o que a reivindicação em dois passos testa. */
  processado_em: string | null;
  tentativas: number;
  erro: string | null;
}

/**
 * Canal de SAÍDA opcional, comum a todo passo que envia mensagem.
 *
 * Ausente/`null` = usa o canal do DISPARO (o número por onde o cliente
 * escreveu), com queda para o canal atual da conversa. Preenchido = força
 * aquele número — é o "envie a confirmação formal SEMPRE pelo número oficial,
 * mesmo que o cliente tenha escrito no celular do advogado".
 */
export interface ChannelScopedStepConfig {
  channel_id?: string | null;
}

export interface SendMessageStepConfig extends ChannelScopedStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig extends ChannelScopedStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

/**
 * Config de `move_deal_stage` e `set_deal_status` (migration 934).
 *
 * Uma forma só para os dois passos: o motor decide qual campo ler pelo
 * `step_type`. Dois tipos quase idênticos custariam mais em ruído do que
 * ganham em precisão.
 *
 * ⚠️ NÃO tem `pipeline_id`. A etapa já identifica o funil
 * (`(stage_id, pipeline_id)` é único desde a 908), e a RPC descobre o funil a
 * partir dela — que é o que permite mover entre funis num UPDATE só, como a
 * trilha da 912 exige.
 */
export interface MoveDealStepConfig {
  /** Etapa de destino, para `move_deal_stage`. */
  stage_id?: string;
  /** Status de destino, para `set_deal_status`. */
  status?: 'open' | 'won' | 'lost';
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  | 'contact_field'
  | 'tag_presence'
  | 'message_content'
  | 'time_of_day'
  /** Compara o canal do disparo com `operand` (um cb_channels.id). */
  | 'channel'
  /**
   * O negócio está NESTA etapa agora? (934) `operand` = `pipeline_stages.id`.
   *
   * ⚠️ Lê o banco, não o contexto — é o que permite "depois de X horas, SE
   * ainda estiver na etapa", o padrão central do funil com espera.
   */
  | 'deal_stage'
  /** O negócio está ganho/perdido/aberto agora? `operand` = o status. */
  | 'deal_status';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

/**
 * Config de `run_automation` e `stop_automation` (migration 936).
 *
 * Uma forma para os dois, como `MoveDealStepConfig`: o motor decide o que
 * fazer pelo `step_type`.
 *
 * ⚠️ `stop_automation` age **só sobre este contato**. Cancelar as esperas da
 * automação alvo para a conta inteira seria um estrago desproporcional: um
 * cliente entrando numa etapa apagaria o follow-up de 24h de todos os outros,
 * sem nada na tela dizendo que isso aconteceu.
 */
export interface AutomationRefStepConfig {
  automation_id: string;
}

/**
 * Config de `run_flow` (migration 936) — o "Executar Robô X".
 *
 * ⚠️ Com robô já ativo no contato, o novo **substitui** o atual (D11): o
 * anterior é encerrado como `stopped_by_automation` /
 * `end_reason = 'replaced_by_automation'`. O invariante de uma run ativa por
 * contato (`idx_one_active_run_per_contact`) continua de pé — e é justamente
 * ele que obriga a encerrar antes de iniciar, senão o INSERT volta 23505.
 */
export interface RunFlowStepConfig {
  flow_id: string;
}

/**
 * Config de `send_media` — enviar imagem, vídeo, documento ou áudio.
 *
 * O arquivo é enviado uma vez pelo builder para o bucket `chat-media` e a URL
 * pública fica gravada aqui. **URL pública permanente foi aceita pelo operador
 * (D12)** — sem URL assinada.
 *
 * ⚠️ **NÃO há coleta de lixo do arquivo.** O mesmo objeto serve toda execução
 * da automação, para sempre. Apagar no envio (como a agendada faz) deixaria a
 * automação quebrada a partir do segundo disparo.
 */
export interface SendMediaStepConfig {
  kind: 'image' | 'video' | 'document' | 'audio';
  /** URL pública que o WhatsApp busca no momento do envio. */
  url: string;
  /**
   * Legenda sob a mídia.
   *
   * ⚠️ **ÁUDIO NÃO TEM LEGENDA, e o dano é silencioso.** A nota de voz sai por
   * `message/sendWhatsAppAudio`, que não possui campo de legenda: um texto
   * aqui seria gravado em `messages.content_text`, apareceria no fio para a
   * equipe e **não viajaria** ao cliente. A regra é barrada na validação e na
   * tela — mesma decisão da migration 932 para a mensagem agendada.
   */
  caption?: string;
  /** Nome exibido ao destinatário. Só documentos; o WhatsApp ignora nos demais. */
  filename?: string;
  /** Canal de saída deste passo. Lido por `stepChannel`. */
  channel_id?: string | null;
}

/**
 * Config de `set_ai` (migration 936).
 *
 * ⚠️ **Religar zera o contador de respostas da IA** (`ai_reply_count`), por
 * decisão do operador (D10). O comentário da rota manual dizia que isso era
 * "não-automatizável de propósito", porque o contador é o teto que impede o
 * robô de responder para sempre numa conversa — e a ação humana, sendo lenta,
 * era a proteção. Automatizado, o teto passa a depender de quem monta a
 * automação: "a cada mensagem recebida, religar a IA" fura o teto para sempre.
 * A decisão é do operador; o aviso fica aqui e na tela.
 *
 * `agent_id` é o encaixe reservado para os agentes de IA nomeados (D7/§4.7 do
 * plano) — hoje o motor o IGNORA. Existe para que a config gravada agora não
 * precise de migração de dados quando a feature chegar.
 */
export interface SetAiStepConfig {
  enabled: boolean;
  agent_id?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | MoveDealStepConfig
  | AutomationRefStepConfig
  | RunFlowStepConfig
  | SetAiStepConfig
  | SendMediaStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  /**
   * Canais (`cb_channels.id`) em que esta automação pode disparar.
   * `null`/ausente = TODOS os canais — o comportamento de antes do
   * multi-canal, e o que toda automação existente continua tendo.
   *
   * Array vazio é estado inválido: significaria "nenhum canal", mas o
   * dispatch o leria como "sem restrição". O trigger
   * `cb_channels_drop_from_automations` (migration 903) normaliza para NULL
   * e DESATIVA a automação quando o último canal do escopo é removido.
   */
  channel_ids?: string[] | null;
  /**
   * Etapas (`pipeline_stages.id`) em que esta automação pode disparar
   * (migration 933). `null`/vazio = TODAS as etapas — mesma convenção de
   * `channel_ids`, nunca "nenhuma".
   *
   * Recorta os gatilhos EXISTENTES pelo estado do funil ("só responda quem
   * está na etapa Proposta"), e é diferente do `stage_ids` do
   * `trigger_config` do gatilho `deal_stage_changed`, que diz para QUAL etapa
   * o card precisa ter entrado.
   *
   * O trigger `cb_stages_drop_from_automations` (933) remove a etapa apagada
   * e DESATIVA a automação se o escopo ficar vazio — array vazio seria lido
   * como "todas", o oposto do que o operador pediu.
   */
  stage_ids?: string[] | null;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
  /**
   * Canal por onde este disparo entrou (migration 903). `null` nos
   * registros anteriores ao multi-canal — a tela mostra travessão, e não o
   * canal padrão, porque naquela época o disparo pode ter vindo de outro
   * número.
   */
  channel_id?: string | null;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Histórico de atividade do lead (migration 912)
//
// Trilha append-only escrita por trigger no Postgres. `authenticated` só tem
// SELECT — nenhum código do app escreve aqui, e tentar escrever devolve 42501.
// ============================================================

export type LeadEventType =
  | 'deal_created'
  | 'stage_changed'
  | 'pipeline_changed'
  | 'status_changed'
  | 'deal_deleted'
  | 'tag_added'
  | 'tag_removed';

/**
 * De onde partiu a mudança. `sistema` é escrita server-side sem ator
 * identificável (API pública, fluxo, manutenção) — o trigger não consegue
 * distinguir esses casos por dentro, e a trilha não deve prometer mais do que
 * sabe. `retroativo` é linha reconstruída pela própria migration.
 */
export type LeadEventOrigin =
  'usuario' | 'conexao' | 'automacao' | 'sistema' | 'retroativo';

export interface LeadEvent {
  id: string;
  account_id: string;
  /** `null` depois que o contato é apagado — o rótulo abaixo sobrevive. */
  contact_id: string | null;
  contact_label: string | null;
  /** Sem FK: `deal_deleted` aponta para um negócio que já não existe. */
  deal_id: string | null;
  conversation_id: string | null;
  event_type: LeadEventType;
  occurred_at: string;
  actor_user_id: string | null;
  /** Nome de quem agiu, congelado no momento do evento. */
  actor_label: string | null;
  origin: LeadEventOrigin;
  from_pipeline_id: string | null;
  from_pipeline_label: string | null;
  to_pipeline_id: string | null;
  to_pipeline_label: string | null;
  from_stage_id: string | null;
  from_stage_label: string | null;
  /** Responde "foi avanço ou foi volta?" — o rótulo sozinho não responde. */
  from_stage_position: number | null;
  to_stage_id: string | null;
  to_stage_label: string | null;
  to_stage_position: number | null;
  from_status: string | null;
  to_status: string | null;
  tag_id: string | null;
  tag_label: string | null;
  tag_color: string | null;
  channel_id: string | null;
  channel_label: string | null;
  /** `true` = linha reconstruída do estado atual, não observada acontecendo. */
  reconstructed: boolean;
  details: Record<string, unknown> | null;
  created_at: string;
}

// ============================================================
// Agenda de reuniões (migration 945)
// ============================================================

/** Onboarding, atualização, ou qualquer outra. */
export type MeetingType = 'onboarding' | 'atualizacao' | 'outra';

/**
 * `falta` = o cliente não apareceu. Fica separado de `cancelada` porque as duas
 * liberam o horário mas contam histórias diferentes sobre o cliente.
 */
export type MeetingStatus = 'agendada' | 'realizada' | 'cancelada' | 'falta';

export interface Meeting {
  id: string;
  account_id: string;
  /**
   * O advogado que atende. Nulo quando ele saiu da conta — a reunião fica no
   * histórico e para de bloquear horário.
   */
  owner_user_id: string | null;
  /** Carimbado na escrita: sobrevive à saída do membro (molde da 925/918). */
  owner_nome: string;
  /**
   * ⚠️ Nulo é caso normal, não defeito: apagar contato faz SET NULL aqui, e
   * reunião interna nasce sem cliente.
   */
  contact_id: string | null;
  contato_nome: string | null;
  conversation_id: string | null;
  /** Por onde avisar o cliente. Usado a partir da Fase 2. */
  channel_id: string | null;
  titulo: string;
  descricao: string | null;
  /** Sala física ou link de videochamada — texto livre. */
  local: string | null;
  tipo: MeetingType;
  /** Instantes, sempre com fuso. Ver `src/lib/agenda/fuso.ts`. */
  starts_at: string;
  ends_at: string;
  status: MeetingStatus;
  /**
   * Fase 4. Nascem nulas e ninguém escreve nelas até a integração com o Google
   * existir.
   */
  google_event_id: string | null;
  google_calendar_id: string | null;
  google_sincronizado_em: string | null;
  google_erro: string | null;
  created_by: string | null;
  autor_nome: string;
  created_at: string;
  updated_at: string;
}

/**
 * Uma FAIXA de atendimento de um advogado num dia da semana. "Seg a sex, 9h–12h
 * e 14h–18h" são dez linhas destas.
 */
export interface Availability {
  id: string;
  account_id: string;
  user_id: string;
  /** 0 = domingo, 6 = sábado — mesma convenção de `Date.getDay()`. */
  dia_da_semana: number;
  /** `HH:MM:SS` no fuso de `timezone`, nunca um instante. */
  hora_inicio: string;
  hora_fim: string;
  /**
   * ⚠️ Nunca implícito. O contêiner roda em UTC; sem esta coluna "9h" viraria
   * 6h em Brasília.
   */
  timezone: string;
  duracao_minutos: number;
  intervalo_minutos: number;
  /** Usados a partir da Fase 2, quando o cliente escolhe sozinho. */
  antecedencia_minima_horas: number;
  janela_maxima_dias: number;
  ativo: boolean;
  created_at: string;
  updated_at: string;
}
